### PR TITLE
add dependabot and github-ci

### PR DESCRIPTION
**Pull request by theavege**
<b>Hello!</b>

Thanks for your app.
I made some minor edits.
I hope they are useful.

<i>Thanks.</i>

### CODE REVIEW

**Comment by dheijl** [comment]
Thanks for this PR! 

I've been considering adding CI, as it certainly makes a project look more professional (but being retired I'm no longer professional and so I kept postponing it).
I noticed the following warnings when running the CI: 
```
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. 
For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default
--
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v2. 
For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default
```
Is this something that can/should be fixed before merging?

**Comment by dheijl** [comment]
Update: upgrade to actions/checkout@v4 makes the warnings go away. Thanks again!

**Comment by theavege** [comment]
[FYI](https://github.com/CM-IV/crypto_rs/pull/2#issuecomment-2403377887)

**Comment by dheijl** [comment]
Thanks for the heads-up. Any comments?

**Comment by theavege** [comment]
Thank you for "upgrade to actions/checkout@v4 makes the warnings go away". 
I'll fix this for [myself](https://gitlab.com/kbit/kbit.gitlab.io/-/tree/palark).

**Comment by theavege** [comment]
I have made this [PR](https://github.com/dheijl/swyh-rs/pull/144) for "upgrade to actions/checkout@vX"

**Pull request merged**
