### PR TITLE
Remove spurious thread

### PR DESCRIPTION
**Pull request by joshuamegnauth54**
`[cpal::Stream]` is asynchronous, so it will play as long as the object is alive. Currently, `swyh-rs` busy waits in two threads for injecting silence. I eliminated both of those threads by storing the stream object in an `Option`.

## Smaller changes
* Added a command line switch to enable or disable the silence injectors
* Refactor `run_silence_injector` into a new module. The function was duplicated across both binaries.

### CODE REVIEW

**Comment by dheijl** [comment]
Looks good to me. One question: any reason why the new inject silence commandline switch is not simply a boolean like the other boolean options?

**Comment by joshuamegnauth54** [comment]
Hm, I didn't notice (or couldn't find) an easy way to enable or disable the silence injector in the configuration file while testing the code. So, I made the switch take an option to explicitly enable or disable the injector.

Should I change it to just a boolean switch?

**Comment by joshuamegnauth54** [comment]
Actually, scratch what I said above. I misinterpreted how the argument parser worked yesterday.

I changed the switch to `bool` like the others.

**Comment by dheijl** [comment]
I copied your idea of relaxed boolean parsing in [this commit](https://github.com/dheijl/swyh-rs/commit/e5c0f5ed09f85a7aef48912d8a9bd154042b951d).

**Pull request merged**
